#@TYPE: Machine
#@NAME: bcm-2xxx-rpi.inc
#@DESCRIPTION: Machine configuration for running a bcm-2xxx-rpi

require bcm-2xxx-rpi.inc
require rpi-graphics.inc

MACHINE_FEATURES += "pci"

EX_KERNEL_DEVICETREE ?= "broadcom/bcm2710-rpi-3-b.dtb broadcom/bcm2710-rpi-3-b-plus.dtb"

KERNEL_DEVICETREE = "broadcom/bcm2712-rpi-5-b.dtb ${EX_KERNEL_DEVICETREE} ${RPI_KERNEL_DEVICETREE_OVERLAYS}"

SDIMG_KERNELIMAGE ?= "kernel_2712.img"
